POST https://polar-basin-25728.herokuapp.com/productos
Content-Type: application/json
{
	"modelo":"Babolat Pure Aero Rafa",
	"descripcion": "Combatividad, resistencia, fortaleza mental... ¡eres como Rafa! Es hora de desafiar a tus oponentes más duros con esta Pure Aero, que con su nombre y colores acompañará tu dominio del juego a través de tu liftado y tu potencia.",
	"stock": 75,
	"precio": 1000,
	"pic": "https://d3ugyf2ht6aenh.cloudfront.net/stores/001/338/510/products/raqueta-babolat-pure-aero-rafa-2-bff1f4ef7c1210fb3b16334515103466-240-0.png",
	"peso": "300 g",
	"aro": "100 in²",
	"patronEncordado": "16/19",
	"grip": "4 3/4 4 1/4",
	"balance": "320 mm",
	"largo": "685 mm"
}

NO SE PORQUE PERO FUNCIONA EN INSOMNIA PERO NO ACA